# Generated by Django 4.2.7 on 2024-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_editors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editors',
            options={'verbose_name_plural': 'Editors'},
        ),
    ]
