# Generated by Django 4.2.7 on 2024-02-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='volume')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, verbose_name='Manuscript title')),
                ('Type', models.CharField(max_length=50, verbose_name='Manuscript type')),
                ('abstract', models.TextField(verbose_name='Manuscript abstract')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Manuscript publish date')),
                ('pdf_file', models.FileField(upload_to='Manuscripts', verbose_name='Manuscript pdf')),
                ('verified', models.BooleanField(default=False, verbose_name='Manuscript verified')),
                ('uder_review', models.BooleanField(default=True, verbose_name='Manuscript verified')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Volume', to='manuscript.volume', verbose_name='Manuscript volume')),
            ],
        ),
    ]
