# Generated by Django 4.2.7 on 2024-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='uder_review',
            field=models.BooleanField(default=True, verbose_name='Manuscript under review'),
        ),
    ]
