# Generated by Django 4.2.7 on 2024-02-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0004_alter_manuscript_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='uder_review',
            new_name='under_review',
        ),
    ]
