# Generated by Django 4.2.7 on 2024-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0006_manuscript_co_authors_alter_manuscript_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='Title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manuscript title'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manuscript type'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Manuscript abstract'),
        ),
    ]
