# Generated by Django 4.2.7 on 2024-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0007_alter_manuscript_title_alter_manuscript_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='m_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manuscript id'),
        ),
    ]
