# Generated by Django 4.2.7 on 2024-02-13 16:19

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Author',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_auth.user',),
            managers=[
                ('author', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
